In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("./resources/spotify2023.csv",encoding='ISO-8859-1')

In [6]:
df.head()

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,144,A,Minor,65,23,80,14,63,11,6

In [7]:
df.columns = ['track_name', 'artist_name', 'artist_count', 'released_year','released_month', 'released_day', 'in_spotify_playlists','in_spotify_charts', 'streams', 'in_apple_playlists', 'in_apple_charts','in_deezer_playlists', 'in_deezer_charts', 'in_shazam_charts', 'bpm','key', 'mode', 'danceability', 'valence', 'energy',  'acousticness', 'instrumentalness', 'liveness', 'speechiness']

In [8]:
#finding null values in each column
print(df.isnull().sum())

# change in_shazam_charts null to 0 and key null to C
df['in_shazam_charts'] = df['in_shazam_charts'].fillna(0)
df['key'] = df['key'].fillna('C')

track_name               0
artist_name              0
artist_count             0
released_year            0
released_month           0
released_day             0
in_spotify_playlists     0
in_spotify_charts        0
streams                  0
in_apple_playlists       0
in_apple_charts          0
in_deezer_playlists      0
in_deezer_charts         0
in_shazam_charts        50
bpm                      0
key                     95
mode                     0
danceability             0
valence                  0
energy                   0
acousticness             0
instrumentalness         0
liveness                 0
speechiness              0
dtype: int64

In [9]:
df.loc[df["streams"] == "218508051"]

Empty DataFrame
Columns: [track_name, artist_name, artist_count, released_year, released_month, released_day, in_spotify_playlists, in_spotify_charts, streams, in_apple_playlists, in_apple_charts, in_deezer_playlists, in_deezer_charts, in_shazam_charts, bpm, key, mode, danceability, valence, energy, acousticness, instrumentalness, liveness, speechiness]
Index: []

[0 rows x 24 columns]

In [10]:
df.loc[df["streams"]== "BPM110KeyAModeMajorDanceability53Valence75Energy69Acousticness7Instrumentalness0Liveness17Speechiness3", "streams"] = 218508051

In [11]:
df["streams"] = df["streams"].astype(np.int64)

In [12]:
# Replace all "," with "" in the in_deezer_playlists column and change the column to in
df["in_deezer_playlists"] = df["in_deezer_playlists"].str.replace(',', '').astype(int)

In [13]:
# convert object having , in in_shazam_charts to int with no ,
df["in_shazam_charts"] = df["in_shazam_charts"].str.replace(',', '').astype(float)

In [14]:
print(df["in_shazam_charts"].value_counts())
#show data with columns track_name and in_shazam_charts only having null in in_shazam_charts
print(df[df["in_shazam_charts"].isnull()][["track_name","in_shazam_charts"]])
#convert NaN to 0
df["in_shazam_charts"] = df["in_shazam_charts"].fillna(0)

in_shazam_charts
0.0      344
1.0       73
2.0       35
3.0       21
4.0       19
        ...
115.0      1
230.0      1
169.0      1
529.0      1
95.0       1
Name: count, Length: 198, dtype: int64
                                 track_name  in_shazam_charts
14                                As It Was               NaN
54                             Another Love               NaN
55                          Blinding Lights               NaN
71                               Heat Waves               NaN
73                          Sweater Weather               NaN
86                        Someone You Loved               NaN
127                        Watermelon Sugar               NaN
158                                   Ghost               NaN
159                     Under The Influence               NaN
180                           Night Changes               NaN
243                             Unstoppable               NaN
274                                 Shivers               NaN
320                      Gangsta's Paradise               NaN
392                               Calm Down               NaN
395                              Space Song               NaN
403                One Kiss (with Dua Lipa)               NaN
410       INDUSTRY BABY (feat. Jack Harlow)               NaN
429                              Bad Habits               NaN
434                                   Woman               NaN
440                                Payphone               NaN
441         All I Want for Christmas Is You               NaN
442                          Last Christmas               NaN
443       Rockin' Around The Christmas Tree               NaN
444                        Jingle Bell Rock               NaN
446                           Santa Tell Me               NaN
449                                 Snowman               NaN
500                              Ã½Ã½Ã½abcdefu               NaN
501                               Sacrifice               NaN
504                             Out of Time               NaN
506               We Don't Talk About Bruno               NaN
507                                   Pepas               NaN
513                                good 4 u               NaN
518                            Need To Know               NaN
519          MONTERO (Call Me By Your Name)               NaN
520                love nwantiti (ah ah ah)               NaN
529                                   MONEY               NaN
531                       Happier Than Ever               NaN
532       Moth To A Flame (with The Weeknd)               NaN
533                                 traitor               NaN
534                                   Toxic               NaN
535                         drivers license               NaN
549                   Love Nwantiti - Remix               NaN
554  Peaches (feat. Daniel Caesar & Giveon)               NaN
560                            Life Goes On               NaN
566                                Dynamite               NaN
584                  Mood (feat. Iann Dior)               NaN
620                            Dance Monkey               NaN
625                                  Arcade               NaN
727            Somebody That I Used To Know               NaN
927     I Really Want to Stay at Your House               NaN

In [15]:
# change in_shazam_charts float to int
df["in_shazam_charts"] = df["in_shazam_charts"].astype(int)

In [16]:
df["in_shazam_charts"].value_counts()

in_shazam_charts
0      394
1       73
2       35
3       21
4       19
      ...
115      1
230      1
169      1
529      1
95       1
Name: count, Length: 198, dtype: int64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   track_name            953 non-null    object
 1   artist_name           953 non-null    object
 2   artist_count          953 non-null    int64
 3   released_year         953 non-null    int64
 4   released_month        953 non-null    int64
 5   released_day          953 non-null    int64
 6   in_spotify_playlists  953 non-null    int64
 7   in_spotify_charts     953 non-null    int64
 8   streams               953 non-null    int64
 9   in_apple_playlists    953 non-null    int64
 10  in_apple_charts       953 non-null    int64
 11  in_deezer_playlists   953 non-null    int64
 12  in_deezer_charts      953 non-null    int64
 13  in_shazam_charts      953 non-null    int64
 14  bpm                   953 non-null    int64
 15  key                   953 non-null    object
 16  mode                  953 non-null    object
 17  danceability          953 non-null    int64
 18  valence               953 non-null    int64
 19  energy                953 non-null    int64
 20  acousticness          953 non-null    int64
 21  instrumentalness      953 non-null    int64
 22  liveness              953 non-null    int64
 23  speechiness           953 non-null    int64
dtypes: int64(20), object(4)
memory usage: 178.8+ KB

In [ ]:
df.to_pickle("./resources/spotify2023.pkl")